name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
        working-directory: sitaram_web
      - name: Analyze
        run: flutter analyze
        working-directory: sitaram_web
      - name: Run tests
        run: flutter test
        working-directory: sitaram_web
      - name: Build web
        run: flutter build web --release
        working-directory: sitaram_web
